version: "3.5"
services:
  graphql-server:
    container_name: graphql-server
    restart: always
    networks: 
      - E-skeleton
    build: .
    ports:
      - "8888:8888"
  graphql-mongo:
    container_name: graphql_DB
    networks: 
      - E-skeleton
    image: mongo
    ports:
      - "27017:27017"

networks:
  E-skeleton:
    name: E-skeleton-graphql